# Generated by Django 2.2.14 on 2024-01-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20240115_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='dist',
            field=models.CharField(default='', max_length=255, verbose_name='行政区'),
        ),
    ]
